# Generated by Django 4.1 on 2022-08-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://cdn-icons-png.flaticon.com/512/1377/1377194.png', max_length=2000),
        ),
    ]
